# Generated by Django 3.2.6 on 2021-08-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XSRConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsr_api_endpoint', models.CharField(help_text='Enter the XSR API endpoint', max_length=200)),
                ('token_url', models.CharField(help_text='Enter the token URL for edX', max_length=200)),
                ('edx_client_id', models.CharField(help_text='Enter the edX client ID', max_length=200)),
                ('edx_client_secret', models.CharField(help_text='Enter the edX client secret', max_length=500)),
            ],
        ),
    ]
